version: "3.4"

networks:
  dev:
    driver: bridge

services:
  product-api:
    image: docker.io/library/productapp:v1.0.1
    depends_on:
      - "product_db"
    container_name: product-api-services
    ports:
      - "5025:5025"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Default=User ID=postgres;Password=postgres;Server=product_db;Port=5432;Database=product_db;IntegratedSecurity=true;
    networks:
      - dev
  product_db:
    image: postgres:latest
    container_name: product_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_db
    ports:
      - "5432:5432"
    restart: always
    volumes: 
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data:
